services:
  relay:
    #image: rikmeijer84/transpher-relay
    build:
      context: .
      dockerfile: docker/relay.Dockerfile
    ports:
      - "${RELAY_PORT}:80"
    volumes:
      - logs:/app/logs
      - data:/app/data
    env_file:
      - .env
    restart: unless-stopped
      
  agent:
    #image: rikmeijer84/transpher-agent
    build:
      context: .
      dockerfile: docker/agent.Dockerfile
    volumes:
      - logs:/app/logs
    env_file:
      - .env
    depends_on:
        - relay
    restart: unless-stopped
    
volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs