services:
  relay:
    image: "rikmeijer84/transpher:latest"
    ports:
      - "${TRANSPHER_PORT}:80"
    volumes:
      - logs:/app/logs
      - data:/app/data
    environment:
      AGENT_KEY: ${AGENT_KEY}
      AGENT_OWNER_PUBKEY: ${AGENT_OWNER_PUBKEY}
      TRANSPHER_PORT: ${TRANSPHER_PORT}
      TRANSPHER_STORE: /app/data
      
volumes:
  data:
  logs: