services:
  relay:
    build:
      context: .
      dockerfile: docker/relay.Dockerfile
    ports:
      - "${RELAY_PORT}:80"
    volumes:
      - logs:/app/logs
      - data:/app/data
    environment:
      RELAY_OWNER_NPUB: ${RELAY_OWNER_NPUB}
      RELAY_NAME: ${RELAY_NAME}
      RELAY_DESCRIPTION: ${RELAY_DESCRIPTION}
      RELAY_CONTACT: ${RELAY_CONTACT}
      TRANSPHER_STORE: /app/data
    restart: unless-stopped
      
  agent:
    build:
      context: .
      dockerfile: docker/agent.Dockerfile
    volumes:
      - logs:/app/logs
    environment:
      AGENT_NSEC: ${AGENT_NSEC}
      RELAY_OWNER_NPUB: ${RELAY_OWNER_NPUB}
      RELAY_URL: ${RELAY_URL}
    depends_on:
        - relay
    restart: unless-stopped
    
volumes:
  data:
  logs: