services:
  relay:
    image: "rikmeijer84/transpher:latest"
    ports:
      - "${TRANSPHER_PORT}:80"
    volumes:
      - logs:/app/logs
      - data:/app/data
    environment:
      AGENT_NSEC: ${AGENT_NSEC}
      AGENT_OWNER_NPUB: ${AGENT_OWNER_NPUB}
      TRANSPHER_PORT: ${TRANSPHER_PORT}
      TRANSPHER_STORE: /app/data
    restart: unless-stopped
      
volumes:
  data:
  logs: