services:
  relay:
    image: nostriphant/transpher-relay
    ports:
      - 8081:80
    env_file:
      - .env
    volumes:
      - logs:/app/logs
      - data:/app/data
    restart: unless-stopped

    
  agent:
    image: nostriphant/transpher-agent
    volumes:
      - logs:/app/logs
    env_file:
      - .env
    depends_on:
      - relay
    restart: unless-stopped

volumes:
  data:
  logs: