services:
  relay:
    image: "rikmeijer84/transpher:latest"
    ports:
      - "${HTTP_PORT}:80"
      - "${RELAY_PORT}:81"
    volumes:
      - logs:/app/logs
      - data:/app/data
    environment:
      AGENT_NSEC: ${AGENT_NSEC}
      RELAY_OWNER_NPUB: ${AGENT_OWNER_NPUB}
      RELAY_URL: ${RELAY_URL}
      RELAY_NAME: ${RELAY_NAME}
      RELAY_DESCRIPTION: ${RELAY_DESCRIPTION}
      RELAY_CONTACT: ${RELAY_CONTACT}
      TRANSPHER_STORE: /app/data
    restart: unless-stopped
      
volumes:
  data:
  logs: