services:
  relay:
    image: "rikmeijer84/transpher:latest"
    ports:
      - "${TRANSPHER_PORT}:80"
    volumes:
      - logs:/app/logs
    environment:
      TRANSPHER_STORE: redis://redis:6379/1
    depends_on:
      - redis
  redis:
    image: "redis/redis-stack-server"
    volumes:
      - redis:/data

volumes:
  redis:
  logs: