name: Build & Push docker RELAY containers

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches:
      - main
      - 'releases/**'

jobs:
  call-docker-workflow:
    uses: nostriphant/.github/.github/workflows/docker.yml@cebbf7a6db054cceb80b653fcfc2ccb5585e1ff1
    with:
      registry_image: nostriphant/transpher-relay
      docker_file: ./docker/relay.Dockerfile
      platforms: linux/amd64,linux/arm64,linux/arm/v7
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
